services:
  - type: web
    name: stock-ft
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./build
    envVars:
      - key: REACT_APP_API_BASE
        value: https://pingpong-backend-at0h.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
